/* FreeRTOS comm 默认配置：小核 CAN 转发 mock 链路使用的私有参数。 */
#ifndef RTOS_CONFIG_H
#define RTOS_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef RTOS_CAN_TX_QUEUE_LEN
#define RTOS_CAN_TX_QUEUE_LEN 32u
#endif

#ifndef RTOS_CAN_RX_QUEUE_LEN
#define RTOS_CAN_RX_QUEUE_LEN 32u
#endif

#ifndef RTOS_CAN_MOCK_RX_QUEUE_LEN
#define RTOS_CAN_MOCK_RX_QUEUE_LEN 8u
#endif

#ifndef RTOS_IPC_MOCK_RX_QUEUE_LEN
#define RTOS_IPC_MOCK_RX_QUEUE_LEN 8u
#endif

#ifndef RTOS_IPC_PAYLOAD_MAX_LEN
#define RTOS_IPC_PAYLOAD_MAX_LEN 128u
#endif

#ifndef RTOS_STATUS_PERIOD_MS
#define RTOS_STATUS_PERIOD_MS 1000u
#endif

#ifndef RTOS_LINUX_HEARTBEAT_TIMEOUT_MS
#define RTOS_LINUX_HEARTBEAT_TIMEOUT_MS 3000u
#endif

#ifndef RTOS_CAN_BITRATE
#define RTOS_CAN_BITRATE 500000u
#endif

#ifndef RTOS_XL2515_OSC_HZ
#define RTOS_XL2515_OSC_HZ 16000000u
#endif

#ifndef RTOS_SPI_INIT_HZ
#define RTOS_SPI_INIT_HZ 1000000u
#endif

#ifndef RTOS_SPI_RUN_HZ
#define RTOS_SPI_RUN_HZ 8000000u
#endif

#ifndef RTOS_CAN_TX_RETRY_MAX
#define RTOS_CAN_TX_RETRY_MAX 2u
#endif

#ifndef RTOS_CAN_LOOPBACK_ENABLE
#define RTOS_CAN_LOOPBACK_ENABLE 0u
#endif

#ifndef RTOS_FAIL_SAFE_LISTEN_ONLY_ENABLE
#define RTOS_FAIL_SAFE_LISTEN_ONLY_ENABLE 1u
#endif

#ifndef RTOS_LINUX_REHANDSHAKE_REQUIRED
#define RTOS_LINUX_REHANDSHAKE_REQUIRED 1u
#endif

#ifndef RTOS_XL2515_MODE_TIMEOUT_POLLS
#define RTOS_XL2515_MODE_TIMEOUT_POLLS 1000u
#endif

#ifndef RTOS_XL2515_TX_TIMEOUT_POLLS
#define RTOS_XL2515_TX_TIMEOUT_POLLS 10000u
#endif

#ifdef __cplusplus
}
#endif

#endif /* RTOS_CONFIG_H */
